Us réservation
WildCodeSchool-2024-09/LILLE-0924-PROJECT2-G1-FLANDRESTO pull request #18
Opened 2024-11-13 09:10 UTC by JuIDO0804

2024-11-13 09:33 UTC, lesage-emeric approved these changes
Ok pour le formulaire de réservation

2024-11-13 10:10 UTC, fantinerudent requested changes

2024-11-13 10:10 UTC, fantinerudent commented on client/src/components/Réservation/Réservation.tsx
> +function Réservation() {
attention accents interdits, nom de fichier et nom du composant !

2024-11-13 10:31 UTC, JuIDO0804 commented on client/src/components/Réservation/Réservation.tsx
> +function Réservation() {
C'est fait, merci de validé

2024-11-14 13:32 UTC, fantinerudent commented on client/src/components/Réservation/Réservation.tsx
> +function Réservation() {
![image](https://github.com/user-attachments/assets/402b0eed-94f2-4f65-b0a3-3bc9cb6d3fcf)
 
non c'est pas fait :D

2024-11-15 09:04 UTC, fantinerudent approved these changes

2024-11-15 09:14 UTC, merged