Us about us
WildCodeSchool-2024-09/LILLE-0924-PROJECT2-G1-FLANDRESTO pull request #3
Opened 2024-11-07 13:45 UTC by lesage-emeric

Mise en place de la structure du composant About us

2024-11-07 13:47 UTC, Supremebatmat approved these changes
Tout est Ok

2024-11-07 14:31 UTC, fantinerudent requested changes
attention aux nommages de vos fichiers; vous avez mis un espace dans about us et pas de majuscule a Us 
![Uploading RaingumpKtoGIF.gif…]()

2024-11-07 16:16 UTC, lesage-emeric commented
J'ai renommé les fichiers

2024-11-08 09:13 UTC, fantinerudent approved these changes

2024-11-08 09:16 UTC, merged