add data.json in router
WildCodeSchool-2024-09/LILLE-0924-PROJECT2-G1-FLANDRESTO pull request #6
Opened 2024-11-07 16:10 UTC by Foub404

Ajout d'un dossier Data.json pour les restaurants

2024-11-07 16:23 UTC, lesage-emeric approved these changes
Everything alright

2024-11-07 16:26 UTC, fantinerudent requested changes

2024-11-07 16:26 UTC, fantinerudent commented on server/src/router.ts
> +router.get("/restaurant", (req, res) => {
c'est une liste de restaurants, mettez un S ! :D

2024-11-08 08:32 UTC, fantinerudent approved these changes

2024-11-08 13:40 UTC, merged